name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up
        uses: actions/checkout@v2
        
      - name: Install Node
        run: npm install
        
      - name: Build Node
        run: npm run build
      
      - name: Configure AWS Credentials
        uses: shinyinc/action-aws-cli@v1.2
        with:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
